
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-29T07:38:07-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "49721a70e230dbd482c6b8e5b75763e0a339f76c",
 "version": "4.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
